manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jewtvet
      url-base: https://github.com/jewtvet
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-ruen
      remote: jewtvet
      revision: bb5e67b99caed2709f8c1ea4d8170fd94c158a72
  self:
    path: config
